### PR TITLE
Add templates for template repository

### PR DESCRIPTION
**Pull request by CaroFG**
Templates need review before creating templates repo

### CODE REVIEW

**Comment by ferdi05** [comment]
@CaroFG Is `SECURITY.md` still needed? Otherwise I'll review your PR

**Comment by CaroFG** [comment]
> @CaroFG Is `SECURITY.md` still needed? Otherwise I'll review your PR

You are right!

**Comment by CaroFG** [comment]
I think it's best to remove the INTEGRATIONS-CONTRIBUTING file, maybe just add a link to it on the readme. Also, if we can put a default code of conduct, I'll remove that file too, which was obsolete anyways...

**Review by ferdi05 — APPROVED** [review]
Awesome, great work @CaroFG 👏
All LGTM
Work on the CoC has not been completed yet, so let's stick with the old one.
I don't really get why you want to get rid of the `INTEGRATIONS-CONTRIBUTING` file could you explain? Thanks

**Comment by CaroFG** [comment]
>  I don't really get why you want to get rid of the `INTEGRATIONS-CONTRIBUTING` file could you explain? Thanks
Because it duplicates the content and if they modify it on their side, it won't be up to date on ours, so I think it's better to just add a link to it

**Comment by CaroFG** [comment]
Are we OK to remove INTEGRATIONS-CONTRIBUTING?

**Comment by CaroFG** [comment]
I am wondering do we actually want this in the devrel repo or do we create a new repository?

**Comment by ferdi05** [comment]
> I am wondering do we actually want this in the devrel repo or do we create a new repository @ferdi05 ?

What do you think would be the most useful for our team? I think cloning a template repo, so I would go for a new repo, but I'm unsure. With issue and PR templates too.

**Comment by CaroFG** [comment]
I would go for a new repo too.

**Comment by CaroFG** [comment]
A template repo has been created: https://github.com/meilisearch/template-repo/
Closing this PR since the content doesn't belong here anymore

**Pull request closed without merging**
